#!/bin/bash

#if ping -c 1 -W 2 $1 > /dev/null; then
#if [ $(curl -sIm1 -w "%{http_code}\\n" $1 -o /dev/null) == "302" ]; then
if [ $(curl -sIm1 -w "%{http_code}\\n" $1 -o /dev/null) == "200" ]; then
echo '{ "full_text" : "    Up  " , "color" : "\#6D91FF"},'
else
echo '{ "full_text" : "    Down  " , "color" : "\#E74C3C"},'
fi
