#!/usr/bin/env bash

OFFSET_RE="\+([-0-9]+)\+([-0-9]+)"

# Get the window position
pos=($(xwininfo -id $(xdotool getactivewindow) | 
  sed -nr "s/^.*geometry .*$OFFSET_RE.*$/\1 \2/p"))

# Loop through each screen and compare the offset with the window
# coordinates.
while read name width height xoff yoff
do
  if [ "${pos[0]}" -ge "$xoff" \
    -a "${pos[1]}" -ge "$yoff" \
    -a "${pos[0]}" -lt "$(($xoff+$width))" \
    -a "${pos[1]}" -lt "$(($yoff+$height))" ]
  then
    monitor=$name
    monitorWidth=$width
    monitorHeight=$height
    monitorOffsetX=$xoff
    monitorOffsetY=$yoff
  fi
done < <(xrandr | grep -w connected |
  sed -r "s/^([^ ]*).*\b([-0-9]+)x([-0-9]+)$OFFSET_RE.*$/\1 \2 \3 \4 \5/" |
  sort -nk4,5)

# If we found a monitor, echo it out, otherwise print an error.
if [ ! -z "$monitor" ]
then
  read totalWidth totalHeight < <(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+)x([0-9]+).*$/\1 \2/')
  c0=$(echo "$monitorWidth/$totalWidth" | bc -l)
  c1=$(echo "$monitorOffsetX/$totalWidth" | bc -l)
  c2=$(echo "$monitorHeight/$totalHeight" | bc -l)
  c3=$(echo "$monitorOffsetY/$totalHeight" | bc -l)
  #xinput set-prop "Genius EasyPen i405X Pen (0)" --type=float "Coordinate Transformation Matrix" $c0 0 $c1 0 $c2 $c3 0 0 1
  set -x
  xinput set-prop "Genius EasyPen i405X" --type=float "Coordinate Transformation Matrix" $c0 0 $c1 0 $c2 $c3 0 0 1
  exit 0
else
  echo "Couldn't find any monitor for the current window." >&2
  exit 1
fi
