#!/bin/bash
output_file="$HOME/.config/xlunch/recent.dsv"
monitor=$(i3-msg -t get_workspaces | jq -r "map(select(.focused))[0].rect")
width=$(echo $monitor | jq -r ".width")
height=$(echo $monitor | jq -r ".height")

if [ "$height" -gt "$width" ]; then
	columns=1
	rows=12
else
	columns=3
	rows=5
fi

focused=$(xprop -root _NET_ACTIVE_WINDOW | grep -o "[0-9a-fx]*$")
if xprop -id $focused | grep -q "_NET_WM_STATE_FULLSCREEN"; then
	xlunch_cmd="xlunch -S -t -a 10 -c $columns -r $rows -b 250 -B 300 -F Raleway_extralight/24 -f Mplus/mplus-2p-light/13 --pc 6d91ffff --tc ccccccff --bc 00000000 -g /home/peter/Pictures/vignette3.png -o -i $output_file --scroll"
else
	xlunch_cmd="xlunch -S -t -a 10 -c $columns -r $rows -b 250 -B 300 -F Raleway_extralight/24 -f Mplus/mplus-2p-light/13 --pc 6d91ffff --tc ccccccff --bc 00000000 -g /home/peter/Pictures/vignette3.png -W -w $width -h $height -o -i $output_file --scroll"
fi

echo $xlunch_cmd

cmd=$($xlunch_cmd)

echo $cmd

if ! [ -z "$cmd" ]; then
  echo "$(grep ";$cmd$" "$output_file")" > $output_file$$
	echo "$(grep -v ";$cmd$" "$output_file")" >> $output_file$$
	mv $output_file$$ $output_file
fi
eval $cmd
